name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox nox-uv
    - name: Run tests
      run: nox -s tests


  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox nox-uv
    - name: Run linting
      run: nox -s lint

  type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox nox-uv
    - name: Run type checking
      run: nox -s type_check
